organization: yfosp
defaultSticker: cluciwd4c06100fl8nkzx8dle
stickers:
  - id: cluciwd4c06100fl8nkzx8dle
    alias: Your-First-Open-Source-Contribution-Badge
  # - id:
  #   alias:
  # more stickers
